FROM python:3.12-slim

# Минимальные системные пакеты
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc && rm -rf /var/lib/apt/lists/*

# Запрет root
RUN useradd -m -s /bin/bash runner

# Код будет монтироваться в /code/code.py
WORKDIR /code

USER runner

# Python безопасный запуск
CMD ["python3", "-u", "/code/code.py"]
